name: Label & comment issues #the name of the workflow
on: # This action will trigger when an issue is reopened or opened.
  issues:
    types:
      - reopened
      - opened
      - closed
  pull_request_target: 
    types:
      - opened
permissions:
  issues: write
  pull-requests: read
        
jobs:
  label_issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: attach label to issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })

      - name: Comment on new issue
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.

      - name: Comment on closed issue
        if: github.event.action == 'closed'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue is now resolved.
# Comment on when an users opens the first pull request 
  first_pr_comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: read
      issues: write
    steps:
      - name: Check if first PR and comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pull_number = context.payload.pull_request.number;
            const creator = context.payload.pull_request.user.login;
  
            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo,
              state: "all",
              per_page: 100,
            });
  
            const openedByCreator = prs.filter(pr => pr.user?.login === creator);
  
            if (openedByCreator.length === 1) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: pull_number,
                body: `Congratulations! @${creator} you are awesome! Thanks for opening your first pull request. We'll review it as soon as possible.`,
              });
            }
